name: Node-CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node: [ '10', '12', '13' ]
        os: [ubuntu-latest, macOS-latest]
    name: Node ${{ matrix.node }} sample
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install, build and test
#      - run: npm install
#      - run: npm test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
